# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['../../navpro/navpro_gui.py'],
    pathex=['../../navpro', '../../'],
    binaries=[],
    datas=[
        ('../../data/input/AIXM4.5_all_FR_OM_2025-10-02.xml', 'data/input/'),
        ('../../data/output/', 'data/output/'),
        ('../../data/samples/20250926_165229_LFXU-LFFY.kml', 'data/samples/'),
        ('../../data/airspaces.db', 'data/'),
        ('../../navpro/profile-correction/', 'profile-correction/'), 
        ('../../navpro/', 'navpro/')
    ],
    hiddenimports=[
        'navpro',
        'navpro.core',
        'navpro.core.flight_analyzer',
        'navpro.core.spatial_query',
        'navpro.core.query_engine',
        'navpro.core.interpolation',
        'navpro.visualization',
        'navpro.visualization.kml_generator',
        'navpro.visualization.kml_styling',
        'navpro.utils',
        'navpro.utils.validation',
        'navpro.utils.search',
        'navpro.data_processing',
        'navpro.data_processing.aixm_extractor',
        'navpro.version',
        'navpro.splash_screen',
        'navpro.config_manager',
        'core',
        'core.flight_analyzer',
        'core.spatial_query',
        'core.query_engine',  
        'core.interpolation',
        'visualization',
        'visualization.kml_generator',
        'visualization.kml_styling',
        'utils',
        'utils.validation',
        'utils.search',
        'data_processing',
        'data_processing.aixm_extractor',
        'aixm_extractor',
        'version',
        'kml_profile_corrector',
        'aviation_utils',
        'kml_profile_viewer',
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.patches',
        'numpy',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.exceptions',
        'requests.models',
        'requests.sessions',
        'urllib3',
        'urllib3.poolmanager',
        'urllib3.connectionpool'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AirCheck',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
